import 'antd/dist/reset.css'
import './globals.css'

import { Inter } from 'next/font/google'

import WrappedConfigProvider from './components/wrappedConfigProvider'
import WrappedBreadcrumb from './components/wrappedBreadcrumb'
import WrappedMenu from './components/wrappedMenu';
import WrappedHeader from './components/wrappedHeader';
import WrappedContent from './components/wrappedContent';
import WrappedFooter from './components/wrappedFooter';
import WrappedLayout from './components/wrappedLayout';


import WrappedBreadcrumbItem from './components/wrappedBreadcrumbItem';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const {
  //   token: { colorBgContainer },
  // } = WrappedTheme.useToken();

  return (

    <html lang="en">
      <WrappedConfigProvider
        theme={{
          token: {
            "colorPrimary": "#ff17ff",
            "colorInfo": "#444444"
          },
        }}
        >
        <body className={inter.className}>
          <WrappedLayout className="layout">
            <WrappedHeader style={{ display: 'flex', alignItems: 'center' }}>
              <div className="demo-logo" />
              <WrappedMenu
                theme="dark"
                mode="horizontal"
                defaultSelectedKeys={['2']}
                items={new Array(15).fill(null).map((_, index) => {
                  const key = index + 1;
                  return {
                    key,
                    label: `nav ${key}`,
                  };
                })}
              />
            </WrappedHeader>
            <WrappedContent style={{ padding: '0 50px' }}>
              <WrappedBreadcrumb style={{ margin: '16px 0' }}>
                <WrappedBreadcrumbItem>Home</WrappedBreadcrumbItem>
                <WrappedBreadcrumbItem>List</WrappedBreadcrumbItem>
                <WrappedBreadcrumbItem>App</WrappedBreadcrumbItem>
              </WrappedBreadcrumb>
              <div className="site-layout-content" style={{background: 'slate'}}>
                {children}
              </div>
            </WrappedContent>
            <WrappedFooter style={{ textAlign: 'center' }}>Ant Design ©2023 Created by Ant UED</WrappedFooter>
          </WrappedLayout>

        </body>
      </WrappedConfigProvider>
    </html>
  )
}
